# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# target 'Runner' do
#   '
#
# # ...
# end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
   pod 'Firebase'
    pod 'GoogleUtilities'
   pod 'FirebaseFirestore', :git=> 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.3.0'
   pod 'Firebase/Core', '>= 0'
   pod 'FirebaseCrashlytics', '>= 0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end



target 'ImageNotification' do
  use_frameworks!
   pod 'GoogleUtilities'
  pod 'Firebase/Messaging','>=10.0.0'
end

#################  Awesome Notifications FCM pod mod  ###################
#awesome_fcm_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications_fcm', 'ios', 'Scripts', 'AwesomeFcmPodFile'), '.symlinks')
#require awesome_fcm_pod_file
#target 'MyAppServiceExtension' do
#  use_frameworks!
#  use_modular_headers!
#
#  install_awesome_fcm_ios_pod_target File.dirname(File.realpath(__FILE__))
#end
#update_awesome_fcm_service_target('MyAppServiceExtension', File.dirname(File.realpath(__FILE__)), flutter_root)
#################  Awesome Notifications FCM pod mod  ###################

# post_install do |installer|
#  installer.pods_project.targets.each do |target|
#   target.build_configurations.each do |config|
#    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#   end
#  end
# end
